version: '3.2'

services:
 wordpress:
   image: wordpress:latest
   ports:
     - 80:80
   environment:
     - WORDPRESS_DB_HOST=wordpress.cpudu0qje6gm.us-east-1.rds.amazonaws.com
     - WORDPRESS_DB_PORT=3306
     - WORDPRESS_DB_USER=wordpress
     - WORDPRESS_DB_PASSWORD=wordpress
     - WORDPRESS_DB_NAME=wordpress

