version: '3.2'

services:
 wordpress:
   image: wordpress:latest
   ports:
     - 80:80
   environment:
     - WORDPRESS_DB_HOST=xxx
     - WORDPRESS_DB_PORT=xxxx
     - WORDPRESS_DB_USER=xxxx
     - WORDPRESS_DB_PASSWORD=xxxxx
     - WORDPRESS_DB_NAME=xxxxx

